# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-17 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=240)),
                ('password', models.CharField(max_length=240)),
                ('accessLevel', models.CharField(max_length=240)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, null=True)),
                ('emailID', models.CharField(max_length=240, null=True)),
                ('mobile', models.CharField(max_length=120)),
                ('otp', models.IntegerField(default=0)),
                ('flag', models.BooleanField(default=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.LoginData')),
            ],
        ),
    ]
