# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-17 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindata',
            name='id',
        ),
        migrations.AlterField(
            model_name='logindata',
            name='ident',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
