# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-17 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200117_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailID', models.CharField(max_length=240, null=True)),
                ('otp', models.IntegerField(default=0)),
                ('flag', models.BooleanField(default=False)),
                ('stop', models.CharField(max_length=20, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resetdata',
            name='emailID',
        ),
        migrations.RemoveField(
            model_name='resetdata',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='resetdata',
            name='otp',
        ),
    ]
