# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-18 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200117_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetdata',
            name='emailID',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
