# Generated by Django 3.0.2 on 2020-01-19 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_resetdata_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetdata',
            name='ident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='login.LoginData'),
        ),
    ]
