# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-17 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseNumber', models.CharField(max_length=240, null=True)),
                ('streetName', models.CharField(max_length=240, null=True)),
                ('area', models.CharField(max_length=240, null=True)),
                ('city', models.CharField(max_length=240, null=True)),
                ('state', models.CharField(max_length=240, null=True)),
                ('country', models.CharField(max_length=240, null=True)),
                ('totalCleared', models.IntegerField(default=0)),
                ('failure', models.IntegerField(default=0)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.LoginData')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseNumber', models.CharField(max_length=240, null=True)),
                ('streetName', models.CharField(max_length=240, null=True)),
                ('area', models.CharField(max_length=240, null=True)),
                ('city', models.CharField(max_length=240, null=True)),
                ('state', models.CharField(max_length=240, null=True)),
                ('country', models.CharField(max_length=240, null=True)),
                ('isCustomer', models.BooleanField(default=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.LoginData')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseNumber', models.CharField(max_length=240, null=True)),
                ('streetName', models.CharField(max_length=240, null=True)),
                ('area', models.CharField(max_length=240, null=True)),
                ('city', models.CharField(max_length=240, null=True)),
                ('state', models.CharField(max_length=240, null=True)),
                ('country', models.CharField(max_length=240, null=True)),
                ('medicalLicenseNumber', models.CharField(max_length=240, null=True)),
                ('hospitalName', models.CharField(max_length=240, null=True)),
                ('speciality', models.CharField(max_length=240, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.LoginData')),
            ],
        ),
    ]
