# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-18 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_resetdata_emailid'),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.DoctorData')),
                ('ident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.LoginData')),
            ],
        ),
    ]
