# Generated by Django 3.0.2 on 2020-01-19 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200119_0150'),
        ('info', '0002_customerdoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkerdata',
            name='ident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='login.LoginData'),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='ident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='login.LoginData'),
        ),
        migrations.AlterField(
            model_name='customerdoctor',
            name='Doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='info.DoctorData'),
        ),
        migrations.AlterField(
            model_name='customerdoctor',
            name='ident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='login.LoginData'),
        ),
        migrations.AlterField(
            model_name='doctordata',
            name='ident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='login.LoginData'),
        ),
    ]
