# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-18 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0004_resetdata_emailid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportID', models.CharField(max_length=240, null=True)),
                ('doctorName', models.CharField(max_length=240, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customerIdent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.LoginData')),
            ],
        ),
        migrations.CreateModel(
            name='ReportContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=240, null=True)),
                ('units', models.CharField(max_length=240, null=True)),
                ('refValue', models.CharField(max_length=240, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ReportID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Report')),
            ],
        ),
        migrations.CreateModel(
            name='TermData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termName', models.CharField(max_length=240, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='reportcontent',
            name='termName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.TermData'),
        ),
    ]
