# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-18 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportID', models.CharField(max_length=240, null=True)),
                ('comments', models.CharField(max_length=240, null=True)),
                ('summary', models.CharField(max_length=240, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporttype', models.CharField(max_length=240, null=True)),
                ('reportKey', models.CharField(max_length=240, null=True)),
                ('reportValue', models.CharField(max_length=240, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reportID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.ReportString')),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='customerIdent',
        ),
        migrations.RemoveField(
            model_name='reportcontent',
            name='ReportID',
        ),
        migrations.RemoveField(
            model_name='reportcontent',
            name='termName',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ReportContent',
        ),
    ]
