# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-19 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20200119_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportstring',
            name='ident',
        ),
    ]
